AllCops:
  Exclude:
    - "vendor/**/*"
    - hexlet-points.gemspec
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/GuardClause:
  Enabled: false

